author: "Tobe O <thosakwe@gmail.com>"
description: "Parser and AST classes for Closure Templates."
homepage: "https://github.com/thosakwe/dart_soy.git"
name: "soy"
version: "0.0.1"
environment:
  sdk: ">=1.19.0"
dependencies: 
  compiler_tools: ^1.0.0-dev
dev_dependencies: 
  test: "^0.12.18"
